### ISSUE TITLE
utf-8-sig???

### ISSUE THREAD

**Issue by jschneier** [jorgebastida/glue#161]
Hi,

I'm using your excellent project as part of a pipeline of things with Django and unfortunately it breaks due to the BOM written out by utf-8-sig (this is for writing out css/scss). Is there any technical reason to keep it around? I'd be happy to submit a pull request to change that if you're amenable to that.

Just submitted the request at #162

**Comment by jleclanche** [comment]
@jorgebastida can you take a look at this? the pr looks good

**Comment by jorgebastida** [comment]
This will be fixed as part of  ``0.11``
