### ISSUE TITLE
Error: PIL identify decoder is unavailable

### ISSUE THREAD

**Issue by berkantaydin** [jorgebastida/glue#179]
I have an error

Error: PIL identify decoder is unavailablePlease read the documentation and install it before spriting this kind of images.

How can solve this ? I using ubuntu x64

**Comment by roycifer** [comment]
i have this problem too every since upgrading to Yosemite.

**Comment by roycifer** [comment]
@berkantaydin i was able to resolve the problem on my mac. there was a lingering "PIL" directory in /Library/Python/2.7/site-packages/. i removed that directory and glue was able to finish successfully.

**Comment by roycifer** [comment]
@berkantaydin wow.. turns out that error was due to a corrupt image! was not due to yosemite at all.
