### ISSUE TITLE
i   reinstall    it    but   still     error    please  help me   thank you  

### ISSUE THREAD

**Issue by zhangdihong** [jorgebastida/glue#180]
weather_rain.png added to sprite
        weather_snow.png added to sprite
        weather_sun.png added to sprite
        webcam.png added to sprite
        webcam_add.png added to sprite
        webcam_delete.png added to sprite
        webcam_error.png added to sprite
        wrench.png added to sprite
        wrench_orange.png added to sprite
        xhtml.png added to sprite
        xhtml_add.png added to sprite
        xhtml_delete.png added to sprite
        xhtml_go.png added to sprite
        xhtml_valid.png added to sprite
Processing 'cut':
Format 'img' for sprite 'cut' needs rebuild...

================================================================================

You've found a bug! Please, raise an issue attaching the following traceback
https://github.com/jorgebastida/glue/issues/new
--------------------------------------------------------------------------------

Version: 0.9.4
Python: 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]
PIL version: 1.1.7
Platform: Windows-7-6.1.7601-SP1
Config: {'css_dir': 'E:\\cut\\dist', 'less_dir': False, 'force': False, 'json_di
r': False, 'crop': False, 'less_template': None, 'css_url': u'', 'global_templat
e': None, 'css_namespace': u'sprite', 'html_dir': False, 'css_cachebuster': Fals
e, 'recursive': False, 'scss_template': None, 'css_pseudo_class_separator': u'__
', 'enabled_formats': ['img', 'css'], 'generate_css': True, 'source': 'E:\\cut',
 'optipng': False, 'follow_links': False, 'imagemagick': False, 'each_template':
 None, 'json_format': u'array', 'watch': False, 'css_sprite_namespace': u'{sprit
e_name}', 'padding': u'0', 'ratio_template': None, 'ratios': u'1', 'caat_dir': F
alse, 'optipngpath': None, 'css_cachebuster_only_sprites': False, 'scss_dir': Fa
lse, 'generate_image': True, 'cocos2d_dir': False, 'imagemagickpath': None, 'alg
orithm': u'square', 'css_cachebuster_filename': False, 'img_dir': 'E:\\cut\\dist
', 'png8': False, 'quiet': False, 'project': False, 'css_separator': u'-', 'algo
rithm_ordering': u'maxside', 'debug': False, 'output': 'E:\\cut\\dist', 'margin'
: u'0', 'css_template': None, 'ignore_filename_paddings': False}
Args: ['C:\\Python27\\Scripts\\glue-script.py', 'E:cut/', 'E:cut/dist']

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\bin.py", line 23
5, in main
    manager.process()
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\managers\base.py
", line 14, in process
    self.save()
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\managers\base.py
", line 45, in save
    format.build()
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\formats\base.py"
, line 40, in build
    self.save(ratio=ratio)
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\formats\img.py",
 line 126, in save
    canvas, kwargs = self._raw_canvas
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\helpers.py", lin
e 58, in __get__
    value = self.func(obj)
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\formats\img.py",
 line 103, in _raw_canvas
    meta.add_text('Comment', self.sprite.hash)
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\helpers.py", lin
e 58, in __get__
    value = self.func(obj)
  File "C:\Python27\lib\site-packages\glue-0.9.4-py2.7.egg\glue\core.py", line 2
16, in hash
    hash_list.append(os.path.relpath(image.path))
  File "C:\Python27\lib\ntpath.py", line 512, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive E:, start on drive C:
================================================================================

**Comment by jorgebastida** [comment]
Sorry, I can't reproduce this bug on my local machine. If you are still experiencing this issue, some more feedback or PR would be more than welcome. Thanks!
