### ISSUE TITLE
Release for python 3 compatibility ?

### ISSUE THREAD

**Issue by NotSqrt** [jorgebastida/glue#185]
Hi !

I see that the code is ready for python 3, when do you plan to release it ?

thanks !

**Comment by jorgebastida** [comment]
Hello, the current version ``0.10`` is compatible with python ``3.3`` and ``3.4``.

**Comment by NotSqrt** [comment]
Great ! Thanks !

I see no trace of the ``0.10`` release on Pypi (I just see the ``0.11`` on pypi, and in my pypi mirror it jumps from ``0.9.4`` to ``0.11``). Was it ever released ?
