### ISSUE TITLE
Allow customisation of the outputted CSS filename

### ISSUE THREAD

**Issue by mattandrews** [jorgebastida/glue#88]
At the moment my choice for the filename of the generated CSS is either controlled by the input directory name (eg `icons.css`) or by using `–cachebuster-filename`, which results in names like `icons_ba0ff1.css`.

I want the cachebusting behaviour for the sprite image file itself, but not in my CSS - my CSS gets concatenated/minified on build, so I just want to always output a file called `icons.css` so I can `@import` it into my main CSS file.

Is this currently possible with glue?

**Comment by frangeris** [comment]
@jorgebastida 3 years later :)...

Executing this do not let me custom the file name of files using `sprite_filename`, it's just a global var, how can I force that file get this name and where can I change the default value?`:

```sh
glue "./source" --force --css-template=./template.jinja --css=./public_html/dist/file --img=./public_html/dist/file
```

Thanks
